jobName: alertmanager-tooling-presubmit
runIfChanged: projects/prometheus/alertmanager/.*
imageBuild: true
commands:
- make build -C projects/prometheus/alertmanager
resources:
  requests:
    cpu: 1024m
    memory: 4Gi
