jobName: prometheus-tooling-presubmit
runIfChanged: projects/prometheus/prometheus/.*
imageBuild: true
commands:
- make build -C $PROJECT_PATH
projectPath: projects/prometheus/prometheus
resources:
  requests:
    cpu: 1024m
    memory: 4Gi
